### ISSUE TITLE
Polls module not working in space

### ISSUE THREAD

**Issue by TheFox** [humhub/polls#121]
1. Browse to Space /s/myspace/
2. Click on Polls button /s/myspace/polls/poll/show.
3. 500 Error

```
2023-03-16 10:54:17 [172.21.25.1][2][ed587febaba8b24c0376e9851b94e509][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: humhub\modules\polls\widgets\WallCreateForm::submitButtonText in /var/www/html/protected/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /var/www/html/protected/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('submitButtonTex...', 'Umfrage erstell...')
#1 /var/www/html/protected/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(humhub\modules\polls\widgets\WallCreateForm), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /var/www/html/protected/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/html/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#5 /var/www/html/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\modules\\...', Array, Array)
#6 /var/www/html/protected/humhub/components/Widget.php(60): yii\BaseYii::createObject(Array)
#7 /var/www/html/protected/modules/polls/views/poll/show.php(14): humhub\components\Widget::widget(Array)
#8 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(347): require('/var/www/html/p...')
#9 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/html/p...', Array)
#10 /var/www/html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/p...', Array, Object(humhub\modules\polls\controllers\PollController))
#11 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('show', Array, Object(humhub\modules\polls\controllers\PollController))
#12 /var/www/html/protected/modules/polls/controllers/PollController.php(46): yii\base\Controller->render('show', Array)
#13 [internal function]: humhub\modules\polls\controllers\PollController->actionShow()
#14 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('show', Array)
#17 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('polls/poll/show', Array)
#18 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#19 /var/www/html/index.php(27): yii\base\Application->run()
#20 {main}
2023-03-16 10:54:17 [172.21.25.1][2][ed587febaba8b24c0376e9851b94e509][info][application] $_GET = [
    'cguid' => '...'
]
```

**Comment by luke-** [comment]
Can you please provide more information? e.g. Polls Module Version, PHP Version, Humhub Version?

Can you reproduce this on our demo hosting?
